=== interactive-instruments/ldproxy/ogcapi-stable/ogcapi-foundation/src/test/resources/schema-draft07.json
{
  "type": "object",
  "title": "Vineyards",
  "description": "The vineyard register constitutes the authorized list of names of single vineyards, vineyards clusters (Großlagen), sub-regions (Bereiche) and wine-growing regions (Anbaugebiete) for the protected designation of origin for wines in the German state Rhineland-Palatinate. It is managed by the Chamber of Agriculture of Rhineland-Palatinate (Landwirtschaftskammer RLP). <br> The data for each vineyard includes the vineyard register number, the wine-growing region, the sub-region, the vineyard cluster, the name of the single vineyard, the village(s), the cadastral district(s) and the area with vines in hectares. The six-digit vineyard register number contains in the first digit the wine-growing region, in the second digit the sub-region, in the third and fourth digit the vineyard cluster and in the fifth and sixth digit the single vineyard.",
  "required": [
    "type",
    "geometry",
    "properties"
  ],
  "properties": {
    "type": {
      "type": "string",
      "enum": [
        "Feature"
      ]
    },
    "id": {
      "type": "integer",
      "title": "Vineyard register number"
    },
    "links": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Link"
      }
    },
    "geometry": {
      "$ref": "https://geojson.org/schema/MultiPolygon.json"
    },
    "properties": {
      "type": "object",
      "properties": {
        "area_ha": {
          "type": "string",
          "title": "Area in hectares"
        },
        "cadastraldistrict": {
          "type": "string",
          "title": "Cadastral district(s)"
        },
        "cluster": {
          "type": "string",
          "title": "Vineyard cluster (Großlage)"
        },
        "date": {
          "type": "string",
          "title": "Validity date",
          "format": "date-time,date"
        },
        "gid": {
          "type": "integer"
        },
        "name": {
          "type": "string",
          "title": "Vineyard name"
        },
        "ogc_fid": {
          "type": "integer"
        },
        "region": {
          "type": "string",
          "title": "Wine-growing region"
        },
        "searchfield1": {
          "type": "string",
          "title": "Search field (option 1)"
        },
        "searchfield2": {
          "type": "string",
          "title": "Search field (option 2)"
        },
        "subregion": {
          "type": "string",
          "title": "Sub-region (Bereich)"
        },
        "village": {
          "type": "string",
          "title": "Village(s)"
        },
        "village_info": {
          "type": "string",
          "title": "Additional information"
        }
      }
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://demo.ldproxy.net/vineyards/collections/vineyards/schema?f=json",
  "definitions": {
    "Link": {
      "type": "object",
      "required": [
        "href",
        "rel"
      ],
      "properties": {
        "href": {
          "type": "string",
          "format": "uri-reference"
        },
        "rel": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "title": {
          "type": "string"
        }
      }
    }
  }
}

=== interactive-instruments/ldproxy/ogcapi-stable/ogcapi-foundation/src/test/resources/feature2.json
{
  "type": "Feature",
  "links": [
    {
      "href": "https://demo.ldproxy.net/vineyards/collections/vineyards/items/410345?f=json",
      "rel": "self",
      "type": "application/geo+json",
      "title": "Dieses Dokument"
    },
    {
      "href": "https://demo.ldproxy.net/vineyards/collections/vineyards/items/410345?f=html",
      "rel": "alternate",
      "type": "text/html",
      "title": "Dieses Dokument als HTML"
    },
    {
      "href": "https://demo.ldproxy.net/vineyards/collections/vineyards?f=json",
      "rel": "collection",
      "type": "application/json",
      "title": "Die Datensammlung, zu der das Objekt gehört"
    }
  ],
  "id": 410345,
  "geometry": {
    "type": "MultiPolygon",
    "coordinates": [
      [
        [          
        ]
      ]
    ]
  },
  "properties": {
    "name": "Niederberg-Helden",
    "area_ha": "29.9",
    "region": "Mosel",
    "subregion": "Bereich Bernkastel",
    "cluster": "Kurfürstlay",
    "village": "Lieser",
    "cadastraldistrict": "Lieser",
    "searchfield1": "Niederberg-Helden/Lieser",
    "searchfield2": "Niederberg-Helden (Lieser)",
    "date": "2020-09-01 00:00:00"
  }
}

=== interactive-instruments/ldproxy/ogcapi-draft/ogcapi-crud/src/test/resources/instant.geo.json
{
    "type": "Feature", 
    "id": 1, 
    "geometry": { "type": "Point", "coordinates": [7.2789399, 50.7772485] }, 
    "properties": {
        "foo": {"instant": "2019-02-05T07:00:00Z"}, 
        "bar": {
            "title": "5209062A5209047O", 
            "href": "https://demo.ldproxy.net/strassen/collections/abschnitteaeste/items/5209062A5209047O"
        }
    }
}
